### ISSUE TITLE
Specification of parameters for jobs

### ISSUE THREAD

**Issue by tarekelgindy** [NREL/jade#26]
Enhancement request:

When submitting jobs, often there is heterogeneity in how many jobs should be summitted per node, or how many processes should be run in parallel (-b -q parameters). Being able to specify these parameters differently for different jobs would improve performance, rather than requiring pipelining or having to oversize node memory to accommodate the worst job.

Then during the scheduling process, jobs with compatible parameters (either the same or possibly under-sized) can be scheduled on the same nodes. e.g. if there are 9 jobs with -b=3 and 10 jobs with -b=4, the scheduler would lauch 3 nodes with 3 jobs on it (from the first set), two nodes with 4 jobs on them (from the second set) and one node with 2 jobs on it (remaining from the second set). 

There are questions around how this would be optimized. For example if there are 10 jobs with -b=3 and 10 jobs with -b=4, could the first set have three nodes with three jobs on them, the second set have two nodes with 4 jobs on them, and then the leftover jobs from each set be placed on a common node since they would have at most three jobs on it? Interested to hear thoughts on this issue...

Being able to specify job-specific parameters for submit-jobs might be nice as well, and may streamline the development process for this.

**Comment by daniel-thom** [comment]
Here is what I'm thinking. Define the notion of `batch groups`. A Jade configuration could have 1 to N batch groups. Each job is assigned a batch group. By default, with no user specification, there is only one batch group and all jobs are in it. The user can assign different submission parameters to each batch group.

If we implemented this, the existing config files would still work. Here is what a config file would look like with multiple batches. For this example assume that all jobs take one hour, some jobs consume all CPUs in the node, and others only consume one. You want to distribute these jobs to different nodes.

```
{
  "jobs_directory": null,
  "configuration_module": "jade.extensions.generic_command.generic_command_configuration",
  "configuration_class": "GenericCommandConfiguration",
  "format_version": "v0.2.0",
  "user_data": {},
  "jobs": [
    {
      "command": "bash my_script.sh 1",
      "job_id": 1,
      "batch_group": "one_core_per_job",
      "blocked_by": []
    },
    {
      "command": "bash my_script.sh 2",
      "job_id": 2,
      "batch_group": "all_cores_per_job",
      "blocked_by": []
    }
  ],
  "batch_groups": [
      {
        "name": "one_core_per_job",
        "num_processes": 36,
        "per_node_batch_size": 144
      },
      {
        "name": "all_cores_per_job",
        "num_processes": 1,
        "per_node_batch_size": 4
      }
  ]
}
```
Each batch group would have its settings applied on top of whatever the user passed as submitter parameters to `jade submit-jobs`.

What do you think?

**Comment by tarekelgindy** [comment]
I think this is a nice clean approach with little overhead.
Sounds good to me!
