### ISSUE TITLE
Report maximum memory usage stats, in addition to average

### ISSUE THREAD

**Issue by elainethale** [NREL/jade#41]
It would be helpful if `jade stats show mem` showed "Maximum" in the per-batch tables and as a summary table across all batches (summary table similar to "Totals" at the bottom of `jade stats show disk`)

**Comment by daniel-thom** [comment]
I actually added this in v0.4.6. Try it out and let me know what you think.

Here is the new help for the command (--summary and --json-summary are new):
```
jade git:(master) ✗ jade stats show --help
Usage: jade stats show [OPTIONS] [STATS]...

  Shows stats from a run.

  Examples:
  jade stats show
  jade stats show cpu
  jade stats show disk
  jade stats show mem
  jade stats show net
  jade stats show cpu disk mem
  jade stats show --summary cpu disk mem
  jade stats show --json-summary cpu disk mem

Options:
  -s, --summary-only  Only show the summary stats per node.  [default: False]
  -o, --output TEXT   Output directory.  [default: output]
  -j, --json-summary  Only show the summary stats per node in JSON format.
                      [default: False]
  --help              Show this message and exit.
```

In case you missed it, also note that `stats.txt` and `stats_summary.json` get auto-generated in the output directory.

**Comment by elainethale** [comment]
Jade development moves quickly! And yes, the new version is along the lines of what I was thinking.
