### ISSUE TITLE
Completed job not getting cleared out of active_hpc_job_ids

### ISSUE THREAD

**Issue by elainethale** [NREL/jade#43]
jade v0.4.9

In this screenshot, you can see that one job is done and two are submitted, but there are still three active_hpc_job_ids:

![image](https://user-images.githubusercontent.com/4871688/129117182-ba24ac38-0106-4381-8258-4b0b32e92502.png)

For reference, here is my HPC queue at the time:

![image](https://user-images.githubusercontent.com/4871688/129117277-19807f68-8ac1-41af-b7be-69aa466ab600.png)

**Comment by elainethale** [comment]
It seems to have cleared itself overnight somehow ...

**Comment by daniel-thom** [comment]
I must have forgotten something about the code. Perhaps you can only see the error if you run the `jade show-status` command. The fixes I described still apply, and I'll implement them next week. Thanks for reporting it.
