### ISSUE TITLE
Add instructions on spark cluster interactive access

### ISSUE THREAD

**Issue by ahcyip** [NREL/jade#74]
Could be useful to add explicit instructions/commands to do this (especially when you're just testing your spark stuff and not sure if it'll work)
https://github.com/NREL/jade/blob/main/docs/source/spark_jobs.rst

-start spark cluster with jade on a bash sleep.sh sleep 14400
-check which node was acquired, ssh into that node
-setup env vars
-access / connect to spark cluster interactively in notebooks, etc.

**Comment by daniel-thom** [comment]
Fixed. Refer to https://nrel.github.io/jade/spark_jobs.html#run-scripts-manually and below.
