### ISSUE TITLE
Local queue

### ISSUE THREAD

**Issue by MRossol** [NREL/jade#8]
@daniel-thom For the ECMWF downloads we want to use Jade to manage our queue of CLI calls WITHOUT making sbatch requests. Instead we just want Jade to submit and manage sub-processes on the login node. Is this already possible? If not could you add it in ASAP (we have a task #)

**Comment by daniel-thom** [comment]
Do you need to rely on the `NREL_CLUSTER` environment variable? JADE uses that to determine what type of HPC to use. If it isn't defined then it will run locally. If you don't need that variable then just remove it.

If you do need that environment variable to be set for some reason then you would need to set the variable LOCAL_SCRATCH to a location where you have write access.

```
unset NREL_CLUSTER
jade config create comands.txt
jade submit-jobs config.json -o output --num-processes=X
# where X is your desired parallelization
```

**Comment by MRossol** [comment]
Thanks @daniel-thom  using unset NREL_CLUSTER did the trick!
